# standard jekyll configuration

title: Open Government Platform
url: http://ogpl.github.io/
repo_name: ogpl.github.io
branch: master

#global settings, no need to change these
root_url: http://ogpl.github.io
org_name: ogpl
prose_url: http://prose.io

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ['README.md']

